import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/Header/Header";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import "@fortawesome/free-brands-svg-icons";
config.autoAddCss = false;

import Script from "next/script";
import Image from "next/image";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <head>
        <Script
          src="https://challenges.cloudflare.com/turnstile/v0/api.js"
          async
          defer
        />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Professzionális vashegesztési szolgáltatások - Minőségi munka, megbízhatóság."
        />
        <title>AcélSzabász.Hu - Főoldal</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900 flex flex-col min-h-screen`}
      >
        {/* Navigation Bar */}
        <Header></Header>
        <main className="font-[family-name:var(--font-geist-sans)] snap-y mt-24 snap-mandatory overflow-y-scroll  h-[calc(100vh-4rem)]">
          {/* Page Content */}
          <Image
            src="/bg-1.jpg" // Replace with your image path
            alt="Background"
            layout="fill" // Makes it responsive
            objectFit="cover" // Ensures it covers the section properly
            quality={80} // Adjust for performance
            className="z-0"
          />

          {/* Proper Dark Overlay */}
          <div className="absolute inset-0 bg-black opacity-80"></div>
          {children}
        </main>
      </body>
    </html>
  );
}
