import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/

import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import "@fortawesome/free-brands-svg-icons";
config.autoAddCss = false;

import Script from "next/script";
import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <head>
        <Script
          src="https://challenges.cloudflare.com/turnstile/v0/api.js"
          async
          defer
        />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Professzionális vashegesztési szolgáltatások - Minőségi munka, megbízhatóság."
        />
        <title>AcélSzabász.Hu - Főoldal</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900 flex flex-col min-h-screen`}
      >
        {/* Navigation Bar */}
        <Header></Header>

        {/* Page Content */}
        <div className="pt-32  flex-grow">{children}</div>

        {/* Footer */}
        <Footer>
          <p>
            {
              "Minden jog fenntartva. Az oldal használatával automatikusan elfogadja a "
            }
            <Link className="hover:underline" href="feltetelek">
              használati feltételeket.
            </Link>
          </p>
        </Footer>
      </body>
    </html>
  );
}
